In [57]:
import numpy as np

d = np.array([[0,8,12,25], [8,0,10,35], [12,10,0,20], [25,35,20,0]])
d

array([[ 0,  8, 12, 25],
       [ 8,  0, 10, 35],
       [12, 10,  0, 20],
       [25, 35, 20,  0]])

In [58]:
h = 1/d
h[h == np.inf] = 0
h

C:\Users\young\AppData\Local\Temp\ipykernel_11512\3889796416.py:1: RuntimeWarning: divide by zero encountered in true_divide
  h = 1/d


array([[0.        , 0.125     , 0.08333333, 0.04      ],
       [0.125     , 0.        , 0.1       , 0.02857143],
       [0.08333333, 0.1       , 0.        , 0.05      ],
       [0.04      , 0.02857143, 0.05      , 0.        ]])

In [59]:
t = np.ones((4,4))
t

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
h_big = h
h_big[:,0] = 0
h_big

array([[0.        , 0.125     , 0.08333333, 0.04      ],
       [0.        , 0.        , 0.1       , 0.02857143],
       [0.        , 0.1       , 0.        , 0.05      ],
       [0.        , 0.02857143, 0.05      , 0.        ]])

In [61]:
h1 = h[0]
h1

array([0.        , 0.125     , 0.08333333, 0.04      ])

In [62]:
h1[0]

0.0

In [63]:
tahb = np.array([t[0][y]*h1[y] for y in range(4)])

In [64]:
tahb

array([0.        , 0.125     , 0.08333333, 0.04      ])

In [65]:
pk = np.array([tahb[y]/tahb.sum() for y in range(4)])

In [66]:
pk

array([0.        , 0.5033557 , 0.33557047, 0.16107383])

In [67]:
cprob = np.zeros(4)
cprob

array([0., 0., 0., 0.])

In [68]:
for x in range(len(pk)):
    indices = [y+1 for y in range(x)]
    cprob[x] = pk[indices].sum()


In [69]:
cprob

array([0.        , 0.5033557 , 0.83892617, 1.        ])

In [70]:
rand_number = np.random.rand()
rand_number

0.0684344900965671

In [79]:
next_iter = 1
for cp in cprob:
    if(rand_number > cp):
        break
    else:
        next_iter = np.where(cprob == cp) + 1
        print(np.where(cprob == cp))
    
next_iter

1

In [81]:
h_big[:, next_iter] = 0
h_big

array([[0.        , 0.        , 0.08333333, 0.04      ],
       [0.        , 0.        , 0.1       , 0.02857143],
       [0.        , 0.        , 0.        , 0.05      ],
       [0.        , 0.        , 0.05      , 0.        ]])

In [83]:
h1 = h_big[next_iter]
h1

array([0.        , 0.        , 0.1       , 0.02857143])

In [84]:
tahb = np.array([t[next_iter][y]*h1[y] for y in range(4)])
tahb

array([0.        , 0.        , 0.1       , 0.02857143])

In [85]:
pk = np.array([tahb[y]/tahb.sum() for y in range(4)])
pk

array([0.        , 0.        , 0.77777778, 0.22222222])

In [86]:
cprob = np.zeros(4)
for x in range(len(pk)):
    indices = [y+1 for y in range(x)]
    cprob[x] = pk[indices].sum()

cprob

array([0.        , 0.        , 0.77777778, 1.        ])

In [87]:
rand_number = np.random.rand()
rand_number

0.49999055158029304

In [96]:
next_iter = 1
for cp in np.flip(cprob):
    if(rand_number <= cp):
        nextIter = np.where(cprob == cp)[0][0] + 1
    else:
        break
    
nextIter

3

<hr>

In [97]:
import numpy as np

d = np.array([[0,8,12,25], [8,0,10,35], [12,10,0,20], [25,35,20,0]])
d

array([[ 0,  8, 12, 25],
       [ 8,  0, 10, 35],
       [12, 10,  0, 20],
       [25, 35, 20,  0]])

In [98]:
h = 1/d
h[h == np.inf] = 0
h

C:\Users\young\AppData\Local\Temp\ipykernel_11512\3889796416.py:1: RuntimeWarning: divide by zero encountered in true_divide
  h = 1/d


array([[0.        , 0.125     , 0.08333333, 0.04      ],
       [0.125     , 0.        , 0.1       , 0.02857143],
       [0.08333333, 0.1       , 0.        , 0.05      ],
       [0.04      , 0.02857143, 0.05      , 0.        ]])

In [99]:
t = np.ones((4,4))
t

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [100]:
h_s1 = h
h_s1[:,0] = 0
h_s1

array([[0.        , 0.125     , 0.08333333, 0.04      ],
       [0.        , 0.        , 0.1       , 0.02857143],
       [0.        , 0.1       , 0.        , 0.05      ],
       [0.        , 0.02857143, 0.05      , 0.        ]])

In [102]:
tahb = np.array([t[0][y]*h_s1[0][y] for y in range(4)])
tahb

array([0.        , 0.125     , 0.08333333, 0.04      ])

In [103]:
pk = np.array([tahb[y]/tahb.sum() for y in range(4)])
pk

array([0.        , 0.5033557 , 0.33557047, 0.16107383])

In [104]:
cprob = np.zeros(4)
for x in range(len(pk)):
    indices = [y+1 for y in range(x)]
    cprob[x] = pk[indices].sum()

cprob

array([0.        , 0.5033557 , 0.83892617, 1.        ])

In [105]:
np.random.rand()

0.8491582720187967

In [106]:
h_s1[:,2] = 0
h_s1

array([[0.        , 0.125     , 0.        , 0.04      ],
       [0.        , 0.        , 0.        , 0.02857143],
       [0.        , 0.1       , 0.        , 0.05      ],
       [0.        , 0.02857143, 0.        , 0.        ]])

In [107]:
tahb = np.array([t[2][y]*h_s1[2][y] for y in range(4)])
tahb

array([0.  , 0.1 , 0.  , 0.05])

In [108]:
pk = np.array([tahb[y]/tahb.sum() for y in range(4)])
pk

array([0.        , 0.66666667, 0.        , 0.33333333])

In [109]:
cprob = np.zeros(4)
for x in range(len(pk)):
    indices = [y+1 for y in range(x)]
    cprob[x] = pk[indices].sum()

cprob

array([0.        , 0.66666667, 0.66666667, 1.        ])

In [110]:
np.random.rand()

0.7247221385578246